//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Requests;
using Ermis.Core.InternalDTO.Events;
using Ermis.Core.InternalDTO.Models;
using System;
using Newtonsoft.Json;

namespace Ermis.Core.InternalDTO.Responses
{
    using System = global::System;

    [System.CodeDom.Compiler.GeneratedCode("NJsonSchema", "14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0))")]
    internal class EventResponseInternalDTO
    {
        [JsonProperty("type")]
        public string Type;
        [JsonProperty("cid")]
        public string Cid;
        [JsonProperty("channel_id")]
        public string ChannelId;
        [JsonProperty("channel_type")]
        public string ChannelType;
        [JsonProperty("user")]
        public UserIdObjectInternalDTO User;
        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt;
    }

}

