//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Requests;
using Ermis.Core.InternalDTO.Events;
using Ermis.Core.InternalDTO.Models;
using System.Collections.Generic;
using System;
using Newtonsoft.Json;

namespace Ermis.Core.InternalDTO.Responses
{

    internal class GetAttachmentResponseInternalDTO
    {
        [JsonProperty("attachments")]
        public AttachmentDataResponseInternalDTO Attachments;
        [JsonProperty("duration")]
        public string Duration;
    }

    internal class AttachmentDataResponseInternalDTO
    {
        [JsonProperty("id")]
        public string Id;
        [JsonProperty("user_id")]
        public string UserId;
        [JsonProperty("cid")]
        public string Cid;
        [JsonProperty("url")]
        public string Url;
        [JsonProperty("thumb_url")]
        public string ThumbUrl;
        [JsonProperty("file_name")]
        public string FileName;
        [JsonProperty("content_type")]
        public string ContentType;
        [JsonProperty("content_length")]
        public long ContentLength;
        [JsonProperty("content_disposition")]
        public string ContentDisposition;
        [JsonProperty("message_id")]
        public string MessageId;
        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt;
        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt;
    }

}

