//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Requests;
using Ermis.Core.InternalDTO.Events;
using Ermis.Core.InternalDTO.Models;
using Newtonsoft.Json;
using System.Collections.Generic;

namespace Ermis.Core.InternalDTO.Responses
{
    internal partial class GetChannelResponseInternalDTO
    {
        [JsonProperty("channels")]
        public List<ChannelStateResponseFieldsInternalDTO> Channels;
        [JsonProperty("duration")]
        public string Duration;
    }

}

