//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Requests;
using Ermis.Core.InternalDTO.Events;
using Ermis.Core.InternalDTO.Models;
using System;
using Newtonsoft.Json;
using System.Collections.Generic;
using Ermis.Core.LowLevelClient.Models;

namespace Ermis.Core.InternalDTO.Responses
{

    internal class MessageResponseInternalDTO
    {
        [JsonProperty("id")]
        public string Id;
        [JsonProperty("text")]
        public string Text;
        [JsonProperty("mentioned_users")]
        public List<UserIdObjectInternalDTO> MentionedUsers;
        [JsonProperty("old_texts")]
        public List<OldTextResponseInternalDTO> OldTexts;
        [JsonProperty("type")]
        public string Type;
        [JsonProperty("cid")]
        public string Cid;
        [JsonProperty("user")]
        public UserIdObjectInternalDTO User;
        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt;
        [JsonProperty("attachments")]
        public List<AttachmentResponseInternalDTO> Attachments;
        [JsonProperty("latest_reactions")]
        public List<ReactionResponseInternalDTO> LatestReactions;
        [JsonProperty("reaction_counts")]
        public Dictionary<string, int> ReactionCounts;
        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt;

    }


    public class OldTextResponseInternalDTO
    {
        [JsonProperty("text")]
        public string Text;
        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt;
    }

    public class AttachmentResponseInternalDTO
    {
        [JsonProperty("type")]
        public string Type;
        [JsonProperty("title")]
        public string Title;
        [JsonProperty("file_size")]
        public long FileSize;
        [JsonProperty("mime_type")]
        public string MimeType;
        [JsonProperty("asset_url")]
        public string AssetUrl;
        [JsonProperty("image_url")]
        public string ImageUrl;
        [JsonProperty("thumb_url")]
        public string ThumbUrl;
    }
}

