//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Requests;
using Ermis.Core.InternalDTO.Events;
using Ermis.Core.InternalDTO.Models;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace Ermis.Core.InternalDTO.Responses
{
    internal partial class QueryUsersResponseInternalDTO
    {
        [JsonProperty("data")]
        public List<FullUserResponseInternalDTO> Users;
        [JsonProperty("count")]
        public int Count;
        [JsonProperty("total")]
        public int Total;
        [JsonProperty("Page")]
        public int page;
        [JsonProperty("page_count")]
        public int PageCount;

    }

    public class UserInfoDto
    {
        [JsonProperty("id")]
        public string Id;
        [JsonProperty("name")]
        public string Name;
        [JsonProperty("avatar")]
        public string Avatar;
        [JsonProperty("about_me")]
        public string AboutMe;
        [JsonProperty("project_id")]
        public string ProjectId;
    }

}

