//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Requests;
using Ermis.Core.InternalDTO.Events;
using Ermis.Core.InternalDTO.Models;
using Newtonsoft.Json;
using System.Collections.Generic;
using System;

namespace Ermis.Core.InternalDTO.Responses
{
    internal class SearchPublicChannelResponseInternalDTO
    {
        [JsonProperty("search_result")]
        public SearchPublicChannelResultResponseInternalDTO SearchResult;
        [JsonProperty("duration")]
        public string Duration;
    }

    internal class SearchPublicChannelResultResponseInternalDTO
    {
        [JsonProperty("limit")]
        public int Limit;
        [JsonProperty("offset")]
        public int Offset;
        [JsonProperty("total")]
        public int Total;
        [JsonProperty("channels")]
        public List<ChannelSearchResultResponseInternalDTO> Channels;
    }

    internal class ChannelSearchResultResponseInternalDTO
    {
        [JsonProperty("index")]
        public string Index;
        [JsonProperty("cid")]
        public string Cid;
        [JsonProperty("type")]
        public string Type;
        [JsonProperty("name")]
        public string Name;
        [JsonProperty("image")]
        public string Image;
        [JsonProperty("description")]
        public string Description;
        [JsonProperty("created_at")]
        public string CreatedAt;
        [JsonProperty("created_by")]
        public string CreatedBy;
    }
}

