//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Responses;
using Ermis.Core.InternalDTO.Events;
using Ermis.Core.InternalDTO.Models;
using Newtonsoft.Json;

namespace Ermis.Core.InternalDTO.Requests
{
    
    internal  class SendEventRequestInternalDTO
    {
        [JsonProperty("event")]
        public EventRequestInternalDTO Event;
    }

}

