//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Responses;
using Ermis.Core.InternalDTO.Requests;
using Ermis.Core.InternalDTO.Events;
using System;
using Newtonsoft.Json;

namespace Ermis.Core.InternalDTO.Models
{
    using System = global::System;

    /// <summary>
    /// Represents user reaction to a message
    /// </summary>
    internal partial class ReactionInternalDTO
    {
        [JsonProperty("message_id")]
        public string MessageId;
        [JsonProperty("user_id")]
        public string UserId;
        [JsonProperty("user")]
        public UserIdObjectInternalDTO User;
        [JsonProperty("type")]
        public string Type;
        [JsonProperty("created_at")]
        public DateTimeOffset CreatedAt;
        [JsonProperty("updated_at")]
        public DateTimeOffset UpdatedAt;

    }

}

