//----------------------
// <auto-generated>
//     Generated using the NSwag toolchain v14.1.0.0 (NJsonSchema v11.0.2.0 (Newtonsoft.Json v13.0.0.0)) (http://NSwag.org)
// </auto-generated>
//----------------------


using Ermis.Core.InternalDTO.Responses;
using Ermis.Core.InternalDTO.Requests;
using Ermis.Core.InternalDTO.Events;
using Newtonsoft.Json;

namespace Ermis.Core.InternalDTO.Models
{
    internal class UserIdObjectInternalDTO
    {
        [JsonProperty("id")]       
        
        public string Id { get; set; }

    }

}

